name: Update pack.mcmeta Description

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  workflow_dispatch:
    inputs:
      description:
        description: "Enter new description"
        required: true
        type: string

jobs:
  update-pack-meta:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update description
        run: |
          DESC="${{ github.event.inputs.description }}"

          jq --arg desc "$DESC" '.pack.description = $desc' pack.mcmeta > temp.json
          mv temp.json pack.mcmeta

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          git add pack.mcmeta

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "chore: update pack.mcmeta description [skip ci]"
          git push
